version: '3.8'

services:
  jmusic-bot:
    build: .
    container_name: jmusic-discord-bot
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
    restart: unless-stopped
    volumes:
      - ./playlists.json:/app/playlists.json
      - ./config.json:/app/config.json
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"